name: Trigger auto deployment for kordatadockercontainer

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/kordatadockercontainer-AutoDeployTrigger-8ba9be27-5e0e-4b94-8bfd-e5989f349f29.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: registry.hub.docker.com
          username: ${{ secrets.KORDATADOCKERCONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.KORDATADOCKERCONTAINER_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: registry.hub.docker.com/servidoreskordata/kordataapione:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.KORDATADOCKERCONTAINER_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n kordatadockercontainer -g kordatatestsvr --server registry.hub.docker.com --username  ${{ secrets.KORDATADOCKERCONTAINER_REGISTRY_USERNAME }} --password ${{ secrets.KORDATADOCKERCONTAINER_REGISTRY_PASSWORD }}
            az containerapp update -n kordatadockercontainer -g kordatatestsvr --image registry.hub.docker.com/servidoreskordata/kordataapione:${{ github.sha }}
